project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: frontend

preserve_hierarchy: 1

files:
  - source: '**/locales/de.po*'
    translation: '**/locales/%two_letters_code%.po'
