name: CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main, develop]

permissions:
  contents: write
  pull-requests: write

jobs:
  changes:
    name: Determine
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            backend:
              - '.github/workflows/cd.yml'
              - 'backend/**'
            frontend:
              - '.github/workflows/cd.yml'
              - 'frontend/**'

  frontend:
    name: Lint and build frontend
    runs-on: ubuntu-latest

    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize environment variables
        uses: Infisical/secrets-action@v1.0.7
        with:
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          project-slug: '${{ vars.INFISICAL_PROJECT_SLUG }}'
          env-slug: '${{ vars.INFISICAL_ENV_SLUG }}'
          secret-path: '/frontend'

      - name: Upload Sources / Fetch Translations
        uses: crowdin/github-action@v2
        with:
          config: frontend/crowdin.yml
          base_path: frontend

          create_pull_request: true
          download_translations: true
          upload_sources: true
          push_sources: true

          pull_request_title: Update Translations
          pull_request_labels: localization
          localization_branch_name: l10n_crowdin_translations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ env.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ env.CROWDIN_PERSONAL_TOKEN }}
