name: CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  changes:
    name: Determine
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - '.github/workflows/ci.yml'
              - 'backend/**'
            frontend:
              - '.github/workflows/ci.yml'
              - 'frontend/**'

  frontend:
    name: Lint and build frontend
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Infisical/secrets-action@v1.0.7
        with:
          client-id: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}
          client-secret: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }}
          env-slug: 'dev'
          project-slug: 'recipe-manager-1vpm
          secret-path: frontend

      - name: Upload Translations
        uses: crowdin/github-action@v2
        with:
          config: frontend/crowdin.yml
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_branch
          create_pull_request: true
          pull_request_title: 'Crowdin Translations'
          pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
